### ISSUE TITLE
Editor Biographies

### ISSUE THREAD

**Issue by RJP43** [RJP43/CitySlaveGirls-ChicagoDailyTimes1888#10]
In addition to completing the tasks of transcription and version linking I posted about in Issue #7 and Issue #9, I would like all of you to create a brief biography to include on the site. 
![screenshot_1](https://cloud.githubusercontent.com/assets/8645521/10870251/15dc29fc-8094-11e5-8a98-795819b1eb81.jpg) This is what I currently have on the site and would like each of you to have something a bit more than what is here. Feel free to include links. To edit your bio. first **sync our Nelson repository** in your Desktop Client. Then in the file explorer find your way to the website folder. The biographies are on the `about.xhtml` page that sits directly inside of that folder. Simply open that file in oXygen and edit your bio. at the bottom of the page then **save**. Don't forget to **commit your changes** and **sync again** on your Desktop Client  so that the file is pushed to GitHub for all of us to see. **Ping me here** with any issues and once you have completed this task!! Thanks!!

**Comment by RJP43** [comment]
@rCarls @spadafour @CodyKarch I would like each of you to please get your biographies in by Friday so at the conference I can show off the diversity of the Nelson Project Team.

@KariWomack thank you for getting yours done. If you check out the site [http://nell.obdurodon.org/about.xhtml](http://nell.obdurodon.org/about.xhtml) there is a link in your bio not working... do you have a working link for the  2015 Fall production of Middletown? Also is there a link for the honor society, even if its just a link for the broader organization like how I link to the international website for Sigma Tau Delta in my bio. ?

**Comment by spadafour** [comment]
Hey, I went into the `about.xhtml`, but it seems that the file up there right now is an old one; it only ls @RJP43 and Shane Daube as contributors currently. And yes, I synced my github before doing this. I even quit github, relaunched, and re-synched. I can add my info to that, but it probably needs to get fixed first. @RJP43, let me know whats up with that.

**Comment by RJP43** [comment]
@spadafour it looks like I don't have the right file synced ... when I get back to the hotel I will resync the right file ... sorry about that ... you can add your bio here in tics or wait an hour or so till I get back

**Comment by spadafour** [comment]
No worries. Hope the trip's going well.

`Rob Spadafore is a Creative and Professional Writing Major at the <a href="http://greensburg.pitt.edu">University of Pittsburgh at Greensburg</a>. He is also editor-in-chief of the school newspaper, <a href="http://insiderupg.com">The Insider</a>.`

**Comment by RJP43** [comment]
The trip is going great so far.. I meet all of the other undergrads in a few hours! Well done with this bio. Thank you! You can check it out on the site here in a few minutes :) 

@KariWomack did you find out about that broken link? And should I add the honor society link I have from above?

@CodyKarch and @rCarls where are you guys in terms of bios. ?

**Comment by RJP43** [comment]
@KariWomack oh I see now it was an image.. in order for it to show up I will need you to upload the image either here or place it into the images folder inside of the website folder and then we can link it like that

**Comment by CodyKarch** [comment]
@RJP43 , I was about to put my into a commit, and it says it won't synch because of "unmerged files" and it shows stuff with the Barkley xmls... I think I posted it, but i'm not sure

**Comment by RJP43** [comment]
@CodyKarch I meant you can put the bio in tic like @spadafour did above in this issue

**Comment by CodyKarch** [comment]
`Cody Karch is a student at the <a href="http://www.greensburg.pitt.edu/">University of Pittsburgh at Greensburg</a>, with plans to transfer to the main campus. His major is English Writing, but will be going into a duel-major in that and Philosophy eventually. Pitt-Greensburg's <a href="http://www.pitt.edu/~ebb8/DHDS/Fall2014-DHSyll.html">Digital Humanities Class</a> is what got him involved with this project. He is helping to transcribe, and support the formation of Nell Nelson project alongside others.`

**Comment by RJP43** [comment]
thanks :) @CodyKarch

**Comment by CodyKarch** [comment]
Yep, and I hope you noticed my other post

**Comment by CodyKarch** [comment]
Hey, @RJP43 , just so you know.. I gave you the wrong link in my description. If you want to change it, here is the CORRECT link: http://newtfire.org/dh/CDASyll.html

**Comment by RJP43** [comment]
@rCarls I still do not have a bio from you ?
