### ISSUE TITLE
Credit for Progress

### ISSUE THREAD

**Issue by CodyKarch** [RJP43/CitySlaveGirls-ChicagoDailyTimes1888#13]
Hey @RJP43 , I was wondering what our tasks for the weeks of 11/20, and 11/27 would be? I believe you would like us to keep working on articles, but I don't know what your say is for the credit in these weeks. Let me know, thanks! 
@rCarls @KariWomack @spadafour

**Comment by RJP43** [comment]
Hey everyone, 

@CodyKarch @spadafour @rCarls @KariWomack  --- for this past week and Thanksgiving week I would like for the few who have yet to commit a transcribed article to do so. As for everyone that has an article done it would be helpful to start coming up with XSLT templates for turning some of these XML files into HTML that will go up on the web. If XSLT isn't your favorite we also still need someone to incorporate [Alex's finding](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/McEnnis_WSGFA_XML/mielnicki_QSetsSanSurvey.docx) into the [XML of the WSGA table from Chapter 1](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/McEnnis_WSGFA_XML/McEnnisC01Table.xml). You could also go back into any of the [transcribed articles](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/tree/master/ChicagoTimes_CSG_XML) and proofread transcriptions fixing any found errors. OR... you could go and try to associate [transcribed articles](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/tree/master/ChicagoTimes_CSG_XML) (maybe all of the articles using the [NYU source](http://dlib.nyu.edu/undercover/city-slave-girls-nell-nelson-chicago-times-aka-white-slave-girls-new-york-world)) with the [transcribed chapters](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/tree/master/McEnnis_WSGFA_XML) from the McEnnis Book (maybe all of the chapters using the [Harvard Source](http://pds.lib.harvard.edu/pds/view/2573582?n=3&s=4&printThumbnails=no)). We are documenting where the articles correspond to the books [here](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ResearchDevelopment/Correlation4Versioning.xlsx). There are a couple of Barkley sections I have yet to correlate as well that could be worked on. 

Thanks Everyone! See you Monday!
