### ISSUE TITLE
Correlate Newspaper Files with Book Files 

### ISSUE THREAD

**Issue by ebeshero** [RJP43/CitySlaveGirls-ChicagoDailyTimes1888#9]
You need a convenient way to tell which newspaper articles go with which portions of the two book publications, so you can line them up together. I'd suggest a Wiki Page first to hold this information for the team.

**Comment by RJP43** [comment]
Post in here linking which Barkley Section(s) you find that correspond with the Original Newspaper Article you were assigned to transcribe @spadafour @rCarls @CodyKarch @KariWomack. 

Thanks :+1:

**Comment by KariWomack** [comment]
I transcribed file 1888-08-09, which corresponds to sections 93-99 in Barkley. The first difference I noticed was that Barkley only had the first two headlines of the article, rather than all five. I also noticed that all of the names, shops, and street names have been cut off. Only the first letters are shown in Barkley.

**Comment by ebeshero** [comment]
Yay! Good stuff, @KariWomack! Have you all been talking about versioning markup--how to code these differences in TEI? If not, I can write up something on how to do it.

**Comment by RJP43** [comment]
@KariWomack well done :) can you go into the [collection folder](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/tree/master/Anon_WSG/BarkleyCollection) and let us know what file in the a.k.a. section corresponds ... I think above you are giving us page numbers from the original text / PDF images.

**Comment by KariWomack** [comment]
Yup, in the collection folder, it was BarkleyS14.

**Comment by RJP43** [comment]
Hey everyone @rCarls @KariWomack @CodyKarch @spadafour , 

I started putting this information into an excel spreadsheet. Simply go [here](https://github.com/RJP43/CitySlaveGirls-ChicagoDailyTimes1888/blob/master/ResearchDevelopment/Correlation4Versioning.xlsx) click on the raw view save the file and open or use you desktop client and go into the ResearchDevelopment folder and you will see the file Correlation4Versioning.xlsx

Thanks! Fell free to add to this file as you complete your transcriptions and determine the related Barkley Section. Also @spadafour I put the article ID numbers in this spreadsheet as well. 

Happy Coding!

**Comment by CodyKarch** [comment]
The Barkley one for mine --1888/8/8 -- was BarkleyS13.

**Comment by RJP43** [comment]
Thanks @CodyKarch

**Comment by RJP43** [comment]
This information now sits inside of our site index ... add accordingly
